Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/zesty64"
  config.vm.provision "shell", path: "scripts/ubuntu-setup.bash"
  config.vm.synced_folder ".", "/home/ubuntu/serve", type: "rsync", rsync__exclude: ".git/"
end
