Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/zesty64"
  config.vm.provision "shell", path: "scripts/ubuntu-setup.bash"
  config.vm.synced_folder ".", "/home/ubuntu/opt/og/src/github.com/alemayhu/2nft/cli-server", type: "rsync", rsync__exclude: ".git/"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = "4"
  end
end
